---
# Source: prometheus/templates/alertmanager-configmap.yaml
apiVersion: v1
kind: ConfigMap
metadata:
  namespace: monitoring
  labels:
    component: "alertmanager"
    app: prometheus
  name: prometheus-alertmanager
data:
  alertmanager.yml: |
    global:
    receivers:
    - name: Nodos
      slack_configs:
      - send_resolved: true
        api_url: 'https://mattermost.management.fravega.com/hooks/mu4ruryuf3ddpp44y1fo6t895r'
        channel: "#Alertas"
        title: '{{ template "slack.default.title" . }}'
        text: |-
          {{ range .Alerts }}
             *Alert:* {{ .Annotations.summary }} - `{{ .Labels.severity }}`
            *Description:* {{ .Annotations.description }}
            *Details:*
            {{ range .Labels.SortedPairs }} • *{{ .Name }}:* `{{ .Value }}`
            {{ end }}
           {{ end }}
        fallback: '{{ template "slack.default.fallback" . }}'
        icon_emoji: '{{ template "slack.default.iconemoji" . }}'
        icon_url: '{{ template "slack.default.iconurl" . }}'

    - name: NodosCritical
      slack_configs:
      - send_resolved: true
        api_url: 'https://mattermost.management.fravega.com/hooks/mu4ruryuf3ddpp44y1fo6t895r'
        channel: "#Alertas"
        title: '{{ template "slack.default.title" . }}'
        text: |-
          {{ range .Alerts }}
             *Alert:* {{ .Annotations.summary }} - `{{ .Labels.severity }}`
              *Description:* {{ .Annotations.description }}
              *Details:*
              {{ range .Labels.SortedPairs }} • *{{ .Name }}:* `{{ .Value }}`
              {{ end }}
             {{ end }}
        fallback: '{{ template "slack.default.fallback" . }}'
        icon_emoji: '{{ template "slack.default.iconemoji" . }}'
        icon_url: '{{ template "slack.default.iconurl" . }}'
      webhook_configs:
        - url: http://prom-sns-alerts:8080/v1/send/ProductionAlerts
          send_resolved: true

    - name: Postventa
      slack_configs:
      - send_resolved: true
        api_url: 'https://mattermost.management.fravega.com/hooks/mu4ruryuf3ddpp44y1fo6t895r'
        channel: "#postventa-alert"
        title: '{{ template "slack.default.title" . }}'
        text: |-
          {{ range .Alerts }}
            *Alert:* {{ .Annotations.summary }} - `{{ .Labels.severity }}`
            *Description:* {{ .Annotations.description }}
            *Details:*
             {{ range .Labels.SortedPairs }} • *{{ .Name }}:* `{{ .Value }}`
             {{ end }}
            {{ end }}
        fallback: '{{ template "slack.default.fallback" . }}'
        icon_emoji: '{{ template "slack.default.iconemoji" . }}'
        icon_url: '{{ template "slack.default.iconurl" . }}'
      webhook_configs:
        - url: http://prom-sns-alerts:8080/v1/send/PostventaAlerts
          send_resolved: true

    - name: Shopping
      slack_configs:
      - send_resolved: true
        api_url: 'https://mattermost.management.fravega.com/hooks/mu4ruryuf3ddpp44y1fo6t895r'
        channel: "#shopping-monitoring"
        title: '{{ template "slack.default.title" . }}'
        text: |-
          {{ range .Alerts }}
            *Alert:* {{ .Annotations.summary }} - `{{ .Labels.severity }}`
            *Description:* {{ .Annotations.description }}
            *Details:*
             {{ range .Labels.SortedPairs }} • *{{ .Name }}:* `{{ .Value }}`
             {{ end }}
            {{ end }}
        fallback: '{{ template "slack.default.fallback" . }}'
        icon_emoji: '{{ template "slack.default.iconemoji" . }}'
        icon_url: '{{ template "slack.default.iconurl" . }}'
      webhook_configs:
        - url: http://prom-sns-alerts:8080/v1/send/ShoppingAlerts
          send_resolved: true

    - name: Marketplace
      slack_configs:
      - send_resolved: true
        api_url: 'https://mattermost.management.fravega.com/hooks/mu4ruryuf3ddpp44y1fo6t895r'
        channel: "#marketplace-monitoring"
        title: '{{ template "slack.default.title" . }}'
        text: |-
          {{ range .Alerts }}
             *Alert:* {{ .Annotations.summary }} - `{{ .Labels.severity }}`
             *Description:* {{ .Annotations.description }}
             *Details:*
             {{ range .Labels.SortedPairs }} • *{{ .Name }}:* `{{ .Value }}`
             {{ end }}
             {{ end }}
        fallback: '{{ template "slack.default.fallback" . }}'
        icon_emoji: '{{ template "slack.default.iconemoji" . }}'
        icon_url: '{{ template "slack.default.iconurl" . }}'
      webhook_configs:
        - url: http://prom-sns-alerts:8080/v1/send/MarketplaceAlerts
          send_resolved: true

    - name: Pricing
      slack_configs:
      - send_resolved: true
        api_url: 'https://mattermost.management.fravega.com/hooks/mu4ruryuf3ddpp44y1fo6t895r'
        channel: "#pricing-monitoring"
        title: '{{ template "slack.default.title" . }}'
        text: |-
          {{ range .Alerts }}
             *Alert:* {{ .Annotations.summary }} - `{{ .Labels.severity }}`
             *Description:* {{ .Annotations.description }}
             *Details:*
             {{ range .Labels.SortedPairs }} • *{{ .Name }}:* `{{ .Value }}`
             {{ end }}
             {{ end }}
        fallback: '{{ template "slack.default.fallback" . }}'
        icon_emoji: '{{ template "slack.default.iconemoji" . }}'
        icon_url: '{{ template "slack.default.iconurl" . }}'
      webhook_configs:
        - url: http://prom-sns-alerts:8080/v1/send/PricingAlerts
          send_resolved: true

    - name: Ccm
      slack_configs:
      - send_resolved: true
        api_url: 'https://mattermost.management.fravega.com/hooks/mu4ruryuf3ddpp44y1fo6t895r'
        channel: "#ccm-alerts"
        title: '{{ template "slack.default.title" . }}'
        text: |-
          {{ range .Alerts }}
             *Alert:* {{ .Annotations.summary }} - `{{ .Labels.severity }}`
             *Description:* {{ .Annotations.description }}
             *Details:*
             {{ range .Labels.SortedPairs }} • *{{ .Name }}:* `{{ .Value }}`
             {{ end }}
             {{ end }}
        fallback: '{{ template "slack.default.fallback" . }}'
        icon_emoji: '{{ template "slack.default.iconemoji" . }}'
        icon_url: '{{ template "slack.default.iconurl" . }}'
      webhook_configs:
        - url: http://prom-sns-alerts:8080/v1/send/CcmAlerts
          send_resolved: true

    - name: Adn
      slack_configs:
      - send_resolved: true
        api_url: 'https://mattermost.management.fravega.com/hooks/z9b14w5tfp8f9mmd79ob58iuhe'
        channel: "#adn-alertas-tech"
        title: '{{ template "slack.default.title" . }}'
        text: |-
          {{ range .Alerts }}
             *Alert:* {{ .Annotations.summary }} - `{{ .Labels.severity }}`
             *Description:* {{ .Annotations.description }}
             *Details:*
             {{ range .Labels.SortedPairs }} • *{{ .Name }}:* `{{ .Value }}`
             {{ end }}
             {{ end }}
        fallback: '{{ template "slack.default.fallback" . }}'
        icon_emoji: '{{ template "slack.default.iconemoji" . }}'
        icon_url: '{{ template "slack.default.iconurl" . }}'
      webhook_configs:
        - url: http://prom-sns-alerts:8080/v1/send/AdnAlerts
          send_resolved: true

    - name: Impuestos
      slack_configs:
      - send_resolved: true
        api_url: 'https://mattermost.management.fravega.com/hooks/mu4ruryuf3ddpp44y1fo6t895r'
        channel: "#impuestos-alerts"
        title: '{{ template "slack.default.title" . }}'
        text: |-
          {{ range .Alerts }}
           *Alert:* {{ .Annotations.summary }} - `{{ .Labels.severity }}`
           *Description:* {{ .Annotations.description }}
           *Details:*
           {{ range .Labels.SortedPairs }} • *{{ .Name }}:* `{{ .Value }}`
           {{ end }}
           {{ end }}
        fallback: '{{ template "slack.default.fallback" . }}'
        icon_emoji: '{{ template "slack.default.iconemoji" . }}'
        icon_url: '{{ template "slack.default.iconurl" . }}'
      webhook_configs:
        - url: http://prom-sns-alerts:8080/v1/send/ImpuestosAlerts
          send_resolved: true

    - name: Logistics
      slack_configs:
      - send_resolved: true
        api_url: 'https://mattermost.management.fravega.com/hooks/mu4ruryuf3ddpp44y1fo6t895r'
        channel: "#oslo-alerts"
        title: '{{ template "slack.default.title" . }}'
        text: |-
          {{ range .Alerts }}
          *Alert:* {{ .Annotations.summary }} - `{{ .Labels.severity }}`
          *Description:* {{ .Annotations.description }}
          *Details:*
           {{ range .Labels.SortedPairs }} • *{{ .Name }}:* `{{ .Value }}`
           {{ end }}
           {{ end }}
        fallback: '{{ template "slack.default.fallback" . }}'
        icon_emoji: '{{ template "slack.default.iconemoji" . }}'
        icon_url: '{{ template "slack.default.iconurl" . }}'
      webhook_configs:
        - url: http://prom-sns-alerts:8080/v1/send/LogisticsAlerts
          send_resolved: true

    - name: Ipos
      slack_configs:
      - send_resolved: true
        api_url: 'https://mattermost.management.fravega.com/hooks/mu4ruryuf3ddpp44y1fo6t895r'
        channel: "#ipos-alerts"
        title: '{{ template "slack.default.title" . }}'
        text: |-
          {{ range .Alerts }}
          *Alert:* {{ .Annotations.summary }} - `{{ .Labels.severity }}`
          *Description:* {{ .Annotations.description }}
          *Details:*
           {{ range .Labels.SortedPairs }} • *{{ .Name }}:* `{{ .Value }}`
           {{ end }}
           {{ end }}
        fallback: '{{ template "slack.default.fallback" . }}'
        icon_emoji: '{{ template "slack.default.iconemoji" . }}'
        icon_url: '{{ template "slack.default.iconurl" . }}'
      webhook_configs:
        - url: http://prom-sns-alerts:8080/v1/send/IposAlerts
          send_resolved: true

    route:
      receiver: 'Nodos'
      group_interval: 1m
      group_wait: 10s
      repeat_interval: 5m
      routes:
        - match:
            severity: postventacritical
          receiver: Postventa
          group_interval: 5m
          group_wait: 5m
          repeat_interval: 5m
        - match:
            severity: shoppingcritical
          receiver: Shopping
          group_interval: 5m
          group_wait: 5m
          repeat_interval: 5m
        - match:
            severity: marketplacecritical
          receiver: Marketplace
          group_interval: 5m
          group_wait: 5m
          repeat_interval: 5m
        - match:
            severity: pricingcritical
          receiver: Pricing
          group_interval: 5m
          group_wait: 5m
          repeat_interval: 5m
        - match:
            severity: critical
          receiver: NodosCritical
          group_interval: 1m
          group_wait: 1m
          repeat_interval: 1m
        - match:
            severity: ccmcritical
          receiver: Ccm
          group_interval: 5m
          group_wait: 5m
          repeat_interval: 5m
        - match:
            severity: adncritical
          receiver: Adn
          group_interval: 5m
          group_wait: 5m
          repeat_interval: 5m
        - match:
            severity: impuestoscritical
          receiver: Impuestos
          group_interval: 5m
          group_wait: 5m
          repeat_interval: 5m
        - match:
            severity: logisticscritical
          receiver: Logistics
          group_interval: 5m
          group_wait: 5m
          repeat_interval: 5m
        - match:
            severity: iposcritical
          receiver: Ipos
          group_interval: 5m
          group_wait: 5m
          repeat_interval: 5m
