---
# Source: prometheus/templates/alertmanager-serviceaccount.yaml
apiVersion: v1
kind: ServiceAccount
metadata:
  namespace: monitoring
  labels:
    component: "alertmanager"
    app: prometheus

  name: prometheus-alertmanager
