---
# Source: prometheus/templates/kube-state-metrics-serviceaccount.yaml
apiVersion: v1
kind: ServiceAccount
metadata:
  namespace: monitoring
  labels:
    component: "kube-state-metrics"
    app: prometheus

  name: prometheus-kube-state-metrics
