---
# Source: prometheus/templates/node-exporter-serviceaccount.yaml
apiVersion: v1
kind: ServiceAccount
metadata:
  namespace: monitoring
  labels:
    component: "node-exporter"
    app: prometheus

  name: prometheus-node-exporter
