apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: thanos-bucket
  namespace: monitoring
spec:
  encryptedData:
    thanos-bucket.yaml: AgA9hnMMEwKpUQx8v8xprKgFub9MrsjTXL15hM79uwijfwN9t99QnEDukLf9jz3cXopCbhBj4z5Gmipw3GtGQjaTkuAlNxRLF+G1ooaDgU/ZJwoHfFUVfGTvtPwD8xOzh3eQyD4n3qYItkXAKVq2JFc1jFWGF1JnCw7yhh/kcrB53tHHaJnOqsZQXj6FWnq1+543UjRx6TCnknEcrhfo3w3uNQ02OGAe4WdqDHZ9F18RWOAuDekRSKGhtss1m16/yywETykIeh0cDaoAwP9Of/yhDtJa6JHyxcyd1VNafVrcE+FzxvXGAPmzyUbAHAr2nERV0NVfHugFvCyUu8GKNZnAtS2b2/YWIUrN5grbLjDDxp+kwRjbUKz7p85iJTr9wIfSAxfUpJRtZV2949R7Qqb7i+dWo/dM6EQ9Z3cZcdLoCDKEDcCKTJ1S1gkRP3wAbQVN69UncjpYL5hMRfI7vpaTpKpQLRL8PtxvlIJVqesdcnP9h5O7F8Zb/IMaeT/5b96xvatrKpgZNS698rRXbeKWpY3mG8Kpgxsl2bNedrxWbb2a0YORdkkjnIbJN3ShL3AqxkdzWfyfn8fT0ce/uixbMJDik7TZPmm57cfsuX9aTkOszKtKeHUHsaNoOFzwRVMQTkvLJ3gmSwP8el4OtIZylHOKGxDZolBaa6bJq4Jx2HJK778v2IjUsFWKv5bnXQxZ5pAMXKxhJl82Q3ax65zf08ds/grtI3mxsD8hIIeSaopmPP5ZDiTwNp1RjghWehUoNm5U06u9D3OOGlsaf9yl1grARrrdK8n2kJ/fCGNHsvywEyfnP5pqB1ouTom+LGcUTdQFQ6c+zGkz9ptNoRdIBdq7tBSgkQaIuJnGsZ9lVTRPtUZkiOghN+BPRrjbwrd33Ai93Of7DytZczde5V5NINvSV/PRa/tRFAWNDR9cKG7Kw3IEbmVcLHcBV4LJSDUZuAeQ3o4fyr5ceXR+GOx3AAJ+hLj9ZpiOR2NnziaNUis3jaBZgju0H7hkggx7oqIXUArKCFgCmDM25nh3+xZMrke8ilQKnA2WKNk32KTpdnO4a8Q7e0skTl152j7kXjmjLeDDPm6LrNtExXkLjU/15aMfGUxbYXACnblwspURNX7vR5qQpoWhz0XViwxE9xjrHBhRO/P3kTj0TCgw4J6xNOfarGn6JGIFYs3vdFjCd5yT2WeX2yPenMNs8o9c
  template:
    data: null
    metadata:
      creationTimestamp: null
      labels:
        app: prometheus
        component: server
      name: thanos-bucket
      namespace: monitoring
