apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: stremio-hpa
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: stremio
  minReplicas: 2
  maxReplicas: 10
  targetCPUUtilizationPercentage: 50