apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: stremio
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
    kubernetes.io/ingress.class: ingress-class
spec:
  rules:
  - host: stremio.k3s
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: stremio
            port:
              name: http