apiVersion: v1
kind: PersistentVolume
metadata:
  name: stremio-pv-volume
  labels:
    type: local
spec:
  storageClassName: manual
  capacity:
    storage: 1Gi
  accessModes:
    #- ReadWriteOnce
    - ReadWriteMany
  hostPath:
    path: "/mnt/data/stremio"
