apiVersion: v1
kind: Service
metadata:
  name: stremio
spec:
  ports:
  - port: 82
    name: http
    protocol: TCP
    targetPort: http
  - name: https
    port: 443
    protocol: TCP
    targetPort: http
  selector:
    app: stremio
  sessionAffinity: None
  #type: LoadBalancer
  #loadBalancerIP: 192.168.64.5
  type: ClusterIP
