apiVersion: v1
kind: Service
metadata:
  name: stremio
spec:
  ports:
  - port: 82
    name: http
    protocol: TCP
    targetPort: http
  selector:
    app: stremio
  sessionAffinity: None
  #type: LoadBalancer
  type: ClusterIP
