apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  annotations:
    cert-manager.io/issuer: cluster-issuer-selfsigned
    cert-manager.io/issuer-kind: ClusterIssuer
    metallb.uniberse.tf/address-pool: default
    nginx.ingress.kubernetes.io/force-ssl-redirect: "false"
    nginx.ingress.kubernetes.io/ssl-redirect: "false"
  name: broidery-backend
spec:
  defaultBackend:
    service:
      name: broidery-backend
      port:
        number: 5000
  rules:
    - host: broidery-backend.k3s
      http:
        paths:
          - path: /unstable/
            pathType: Prefix
            backend:
              service:
                name: broidery-backend-canary
                port:
                  number: 5000
          - path: /stable/
            pathType: Prefix
            backend:
              service:
                name: broidery-backend
                port:
                  number: 5000
  tls:
    - hosts:
        - broidery-backend.k3s
      secretName: broidery-backend.k3s.cloud-tls
