apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

patches:
- path: deploy.yaml

images:
- name: localstack/localstack
  newTag: latest-arm64

resources:
- ../../base

namespace: localstack