apiVersion: v1
kind: Service
metadata:
  name: discord-bot-svc
spec:
  ports:
  - port: 80
    protocol: TCP
    targetPort: http
  selector:
    app: discord-bot
  sessionAffinity: None
  type: ClusterIP
