apiVersion: apps/v1
kind: Deployment
metadata:
  name: broidery-frontend
spec:
  replicas: 2
  selector:
    matchLabels:
      app: broidery-frontend
  template:
    metadata:
      labels:
        app: broidery-frontend
    spec:
      containers:
      - image: spirito/broidery-fe:latest
        name: broidery-frontend

