apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: broidery-frontend-hpa
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: broidery-frontend
  minReplicas: 1
  maxReplicas: 10
  targetCPUUtilizationPercentage: 50