apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

patches:
- path: deploy.yaml

images:
- name: spirito/broidery-fe
  newTag: k3s

resources:
- ../../base
- hpa.yaml
- ingress.yaml
- jobs.yaml

namespace: default