apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
metadata:
  annotations:
    argocd.argoproj.io/autopilot-annotation: "true"
    argocd.argoproj.io/depends-on: |
      [
        {"name": "broidery-backend", "namespace": "default"}
      ]

patches:
- path: rollout.yaml
#- path: deploy.yaml

images:
- name: spirito/broidery-fe
  newTag: "1.0"
- name: alpine/curl
  newTag: latest

resources:
- ../../base
#- hpa.yaml
- ingress.yaml
- ingress-bg.yaml
#- jobs.yaml

namespace: default