---
apiVersion: argoproj.io/v1alpha1
kind: Rollout
metadata:
  name: broidery-frontend
spec:
  revisionHistoryLimit: 1
  replicas: 2
  selector:
    matchLabels:
      app: broidery-frontend
  template:
    metadata:
      labels:
        app: broidery-frontend
    spec:
      containers:
      - name: broidery-frontend
        image: spirito/broidery-fe:latest
        imagePullPolicy: IfNotPresent
  strategy:
    blueGreen: 
      activeService: broidery-frontend
      previewService: broidery-frontend-canary
      trafficRouting:
        nginx: 
          stableIngress: broidery-frontend
          additionalIngressAnnotations:   
            canary-by-header: X-Canary
            canary-by-header-value: wepa
      steps:
      - setWeight: 30
      - pause: {}
      - setWeight: 60
      - pause: {}
      - setWeight: 100
      - pause: {}     