apiVersion: v1
kind: Service
metadata:
  name: broidery-frontend
spec:
  ports:
  - port: 80
    protocol: TCP
    targetPort: http
  selector:
    app: broidery-frontend
  sessionAffinity: None
  type: ClusterIP
