apiVersion: apps/v1
kind: Deployment
metadata:
  name: vault
spec:
  replicas: 1
  selector:
    matchLabels:
      app: vault
  template:
    metadata:
      labels:
        app: vault
    spec:
      containers:
        - name: vault
          image: hashicorp/vault:latest
          ports:
            - containerPort: 8201
              name: http
          env:
            - name: VAULT_ADDR
              value: http://localhost:8200
            - name: VAULT_API_ADDR
              value: http://localhost:8200
            - name: VAULT_LOCAL_CONFIG
              value: '/vol/vault/config/vault.hcl'
          command:
            - vault
            - server
            - -config=/vol/vault/config/vault.hcl
          readinessProbe:
            httpGet:
              path: /v1/sys/health
              port: 8200
            initialDelaySeconds: 50
            periodSeconds: 5
          livenessProbe:
            httpGet:
              path: /v1/sys/health
              port: 8200
            initialDelaySeconds: 10
            periodSeconds: 10
          volumeMounts:
          - mountPath: /vol/
            name: config
      volumes:
        - name: config
          configMap:
            name:  vault-config
            items: 
              - key: vault.hcl
                path: vault/config/vault.hcl