apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: vault-ingress
spec:
  tls:
    - hosts:
        - vault.k3s
      secretName: vault.k3s.cloud-tls
  rules:
    - host: vault.k3s
      http:
        paths:
          - pathType: Prefix
            path: /
            backend:
              service:
                name: vault
                port:
                  name: http