apiVersion: v1
kind: PersistentVolume
metadata:
  name: vault-config
  labels:
    type: local
spec:
  storageClassName: manual
  capacity:
    storage: 1Gi
  accessModes:
    #- ReadWriteOnce
    - ReadWriteMany
  hostPath:
    path: "/vault/config/vault.hcl"
