apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: vault-config-claim
spec:
  storageClassName: manual
  accessModes:
    #- ReadWriteOnce
    - ReadWriteMany
  resources:
    requests:
      storage: 1Gi
