apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: db-secret
  namespace: default
spec:
  encryptedData:
    MYSQL_PASSWORD: AgCopAyP1ZxCE6LtJSJFBU+yQ+SARMRjuqRnu3niB2omYMvp03BAW9n+fo1DgjWN7oGjmxrl8zIg6UCNMT1JDMbx7yABYUJYSOGHJcNMvvAnzd6q9EtawPEfu7awx3RoCpv7uNh7259QVj7Ytkc875nspkL8R+LEd7NtBAa0FkFLXN8iRoB4Hr2o8WLpTlNuen3yEaVdAGGmPex8OMUwB0f74c2mPXFNf9hrlHIWHxK3M77XRAfcU4ttjzr3W4rUkePPDGSbBobciF4WjDPgZqIpOQlKeMdGeur2HqI4fC5/yTNDw43gsHOgkZlpTvCYzYhSZTtoCcGjeHx96zAH5iVgDi0V2YVCR601vGaYFdvcm+4stGNkdxBuISTDQU9KJdBbkPXrJheaP5amgprPUBrNFLN/1p+eOWLrg5WWr2cLNjC/yoYJE96gCQvTKBkMJDWOEji+MMBPrVkzMS2/fyjPp6hzeA6yZgHS67lwdntgxxO+n2g4EVmLLRDcOhvdIJDW7vq01yiIUZ2fYJv81CdElaTCZ3fPh5T0eDLCvhCDCgQnnj4mV7aiz3tPwYC6bVgrnZkPuUQFuMCPsyLDlesqnlT1VDmHBdTYJfoadhOz9IBTuI/L3IH3aP8YQgZ9vCAu2KlT4kisPJkoGzYSnRD/FD13pRXWxai8IUjlTlcsWtknV+VUh/VN86fxW5GCiS/Rd3/0u8pkHV6HIJWWoG3fxw==
    MYSQL_ROOT_PASSWORD: AgB7hdYgBsrMmuwU/SxID5GqYrr2KH55W6+eTCX6aoKMmG8MqDAEtxnXBtwIf1C243YtcV0yjpgsUf1k+JbGBj9MUd0/SLk1s/aP2st34KisSwSenp8EIexRTjcvoR/omMXVOWcHhUwOC7l8HIAa2WU49I0N6y7xi49QfaaduqqlcXKuRsbXPQ/noP+9RKBWVRMUsA4L5lRa1ewxabihKBlyvjH8r9P10k+qNwwZLqIyAp/2LoE3MWT1PfxUoJFQl22LIPp4oWNCzm6KdriMOgrjcF16kHgtuIpBhjywTiiY5gCsmBkl5BzV5SI6khO1UBrJnv02WNWqfOKlRLkiHgo0cFqc/8aBw+KrjLFkrvPsZ+TmjVVrRcmWdlxe2Ay5KRTbNLj8oOtRM7N0Q7BLc9J0Eew24EUIVvtZu3jg/s4CXoEZNyzmCGdroO241e4zCQEOEJ9m8g8ZJbyyjHzJllsfUepIx+sRNXfls02ro4RqLEb0DD4XTHrgve608A/f/OtcWrVh94HQHovstiuSoE8meio5/PIqGG0cvgk+vmaiSfdMXXXLSQDq+s4sWMxgvqUuoxA7ThoA+Q4LW9zOx7Z4+n3pe/Zi4cm7Ym1m11L3jadZofuZ4PYoXLkgkwbks89vIC9+qiLUMhKGDQTAFj3a/1SJdEADuO/7XDo6XPlMj/wKo/splHX0TQufZY0hNvAdo3I5V9d0pbXPckMK+iO5Ng==
  template:
    metadata:
      name: db-secret
      namespace: default

