apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: db-secret
  namespace: default
spec:
  encryptedData:
    MYSQL_PASSWORD: AgBlkJa6DixpzPXikZxiu4BjnuLEJnJizVFHIRPD9Xmzu5Q4KDpWE6ZiN24Kk47fJZkI9HajPv1IVzAnP+dk6byo9NKzwZA6/bvI6ETxpPReUOGT6AOIuWFjEBrlWlZ1/UkcBXcCRmKCcqrvtkYmzQkoNibDZ5D681b+WM0w6Qjc5eQk6pZqgIgk8Fa5QJZpejzDUdVOw8ZC98qADQ98cl2YoejVZIsneHWlrUIgZj8Cb3aHHX2pZSjvdrUmoawnMsijfYW2nkQiS3El4KwkrD8BVh/O63hXZZ6OZUgNsJwLdzKflv+0dtCO1sydw1FZmkcEIPljUeDUA+qT8jSsd+t1fMAPJj1ICNy4UqWgYuuysJeijRTsvczLJsOlQWJmP91eOzw2t4dUFlF8Mkq308Jg1a1Sj7kifIfFDtDpy6yFJI4T6XaJc1Cmv5NL+xI5cfPaaul4R+DTqJVsdVVHPH4C5HZSuLrp/vu8zGP8p5CNtt4gJxOM84yAT4wpmzdzc5AVd/KMLVL/CR8gdFp7m/hrSk5aSVIhWBMlj1+njBR51rGdFpS3oDwCLp/T0rnmCRRb7AIYh6J/3k0hpVAR+9vdxLYT/Vf51gUhVBKALFpt1t7qgp3jeN2l8RbN5lsmYIh4omRGHJORxBKmHqEub9VokteP8QMUSCinYb9Wpa9EcPvrjOqnj9JUp7KUkRSitbupdZUXtVz7X6VKJB57Z1l+Sw==
    MYSQL_ROOT_PASSWORD: AgBX9KzfJCDydbvoKWSff7dEMudkW+50ndVJnjIxJFA8F6JXb/6ULffP57TRl4N/sTYKvCY5JJN0fdAiyF1ZwTHi3AJrSoa/8k4IX4urOeM8QbwSIKVZsYaesVUFXwKEPkPNKu7Bucc77vfQXqhL3ZI6B9CjaJRg9LGKXu40bD9U5JrvUzgWgpiPYmbi4Z2noG1N1VW2ybPwbSsv+rsv1F7QIyPExHfcdK6cvgzKgARJbFVDJ4U/uf0tn7LYbaOTMVOQliogvyLjj5FNGJxb3KcCEY+WihFNMvSa26LWHoyjBGx2Mhbhi7jEO8Iuadpp4XDrOgM4r8QFMuqwciKGPHLc2uw8IgJik67mCX1ZiFA0h48v6Eq2XCJrBi7DPPTYDjYpckzYg1mJ0OfIhfEKWQkRoMglDzy+T4fRWlF7ALY+SX11UVKEaocFp554eYzc5l4t+ZxQWNG4Qn+5cD1nfXwUCFKCmHkbqCHkVvCBia7NB6qkJH4R87oPK5hH20Ccx/9U6/0sh4KH2+RGMGak10aFfhi0BXmsMOfEaYH5P5WuolD7ekO0OQ6TxNJnUQGLvFsVfnzYRqj/oynOgC5xKCHauY4DdCAKRzGnog4hcWHWPAWc23O1nntsTD1WCHhXNxAaVykETq3uBlJ0Oen7bRW00AZ65RI/MnPtgT/aTkZELs7hI43Tcfx+WDQyjFGj5Ra+lHaRR7KwULRluuHQEQvUVg==
  template:
    metadata:
      name: db-secret
      namespace: default

