apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: db-secret
  namespace: default
spec:
  encryptedData:
    MYSQL_PASSWORD: AgC2t4qnA1aFvl3zx2PWSJYPqsdSPACmNakjVjBDTlLEaQxAG6csmiDyT0/TRnI1Ll/vM42/rwV1T3NGNThkF6fgDjSHbaqZ/DSG0L1wInZYoWz/s3ykhK13/uf8pXD/Izhth6URu+5IXKoHdOq24J7VP/hSg5ci02xcVfoAixTNTCzeDPximemVeM7ylK7SqOso41KTh6KVXxoMjdjSCQu1t8rDC7AKZol/+/D3SGJ+FTLzbOy5VVDKzKjHEVw6PD7MlZ/6TNA8geUYPeJ5UNSC8mCKOY3gS9+h9lk/3H1pQXEFpWk1nx2xRTHaBExUpgv6boF/OJkaMsMoDDGLHnVVQRiBdL3fIIwWLQD00T+vee/BrmeZeuNtgiFzkXgchPreX+uameaH6qwF9AXz1K4awrUfHnD5ph25eUpckFmVuyxDAql5xYeCRVYJNkXgiYglIabQUyyQS+g557d7WKgIHK/uOE2B4UlCqyFvxF3LMS7jLCUztuStYxLhSYgApN728L3qQX0iSY9k/d7sTGiAZUO2xcULz+GVxOoVb8ahlKAeOGy0q1vQP6wPd1e8wB61zpImH8T/6uEqxoqFWuvq2dXczbiY5jVrKQyJadmeS/hVKbqc6DyCtZ6KL1Egq1NufSC2zejtv+v/bsbwnbP1PYGu36xPahizHYUesWCJ5hu8L4LNjqhTKn9IHRDWOGfUfVoBrDeqpMbnRar9oJMz
    MYSQL_ROOT_PASSWORD: AgAPki85SEIIOowPQ8yjvJ8k1mH9hkIcugHZBlDL5lCVVO4LYfbFe+a7wjDgaoUsjvfzLC82JhbZsHUWkfhfrmK45B6p9j6ZvgyfiWk0sHufvmwFKEvvjJeh3vWyvhUuq8c0nbXWkn/G9Z72bbJSlpyncqztyy5HM/cLkZqr7Ow30sQZhTQTmNqHAG9yNGvh6V2kp8zQxvYkI+reX0zq8WrXC8YWwHRdTba6yl7pfH+2kaqqKUiL87PIGm+UbZjjZmpU9Rgp6YuRm3d1E5Bf/iM9jx/lhkFOBhyWhTazBLmC06CU5oPXy5P6aHCGY5S6kQzKtLXgMTjHScqbaALXbePJU9QiM2MIVyxVS7HY6VtxcEFBr8dFbhmUEjwcDChfQSIOqvSlnE3SQ0QnvdY6E/Wk2nKwXyrhEKLPl9uIzHuuQM0UHo8N1XEJ7oUFRGG3euhVzR+bu3KjgYW1Ewr1b6jc0U5daLJ9/JJb7L+a4TrgGd4DfylfbnD9TjLXvL5m0beNizjutDsMG0ZQItXj0iWOrBd0iAgJzNUPMtP1nUE/JzhOndcoowBESnJhgV5QVqOOwgmWkv42+J68CX4FM1rryRO+TRDe3eRNc5ExuIJueYBtGGuenCSKI0xat4rw2gJcYZcVGPh5WbfsBFshAMKQPX5VMxe9xWST+6wACxsPya8SGauVswOffQXAcpGpr1KUK1XY2NwfuizkNzv4R5GI
  template:
    metadata:
      name: db-secret
      namespace: default
    type: Opaque

