apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: db-secret
  namespace: default
spec:
  encryptedData:
    MYSQL_PASSWORD: AgBI0L/yQBCQBzIjfMzOPjk7gg6k8FqC+cglWuBWmhicUNzJ+yg11qU6y4GjAzgLkk13ftxmMVUG8mOHnbjAXuFmS8dIYe0Qq5D/3XP3QWh6UF7cdx3xr6rXP49uK7jRa6R6YGqgqKv89ZlzCfl/dvy/JuZeItqB4+S0HTG8GANBosE3HRQQO4mrU4k9t+8riuSBAQtw0gYMPs/c/jIKlkZNlp7A55we5fF0ZV0k6LS/923lpGiGyxL+B6oiyKcCkSTGdX1Aga54zIuE2n7BmtmPc30YdBxCgFAS2Is7MWSNOsELzICxAKhd9Kq3SKcwVMi6EYSXXqupm/CBKj1msQl93tkPTXj18/e8tgwTuo7Jd3BZ1Me98WiA8ZY3wTaHuk9UR/s35rmMcV50o+7VMxZEh8na85Vt7MpDOQlxhP98HpEq6APHIzShbdXRn8ZtmBjsoIqVLLEV1GmBUQJaTB6dHfM7LRWjuZXXq03sMkUh7H8UCYXqkCI1ei3VZaZzZSnKJs1lVjyq3S17y6hQ2uNilDXg9YKerh7f6Ixvjk1YFV74RmUs51cRbNC88kytMj1+p/BSzblF6t/q6mA1BWPM/M2MIMlL6H95K8YJB6pbbx5TjTYUtdo9JeeVzU9R6rA0RyYebL/hlEGvYmsM5SA57DDlQIfyRQXVC5ruZd/MVsv1rt5woxT/muJChnyVNuDxHHgKZj6v/wnORX2ZD2IL
    MYSQL_ROOT_PASSWORD: AgDwbJJySqD1gsk56J4z+LyBvt51V7LEJZ1nSarT3/+ERrFQk6Hc/0Ar/ZzWKu/kVM7GyNaf5uqBCSRzd0rBmzW0qncsfOMd5ZGHLOAN/hZVq6WH7USdFfOYoSlSE0c5R1WoBNZuorfiBew/lEQ58OyvP6QB2xTFfhaSEL7FJ8AfUD9T8MA/WpCRUg43JHbipWhk4mhGTQl+EaY3cDLMg7+yLJAhXysQkIzTgoc+AR2Cf0TU3T2mBfQVO+q9EOOgk1UixkImgZrX5C6GbtEovlpL1m1HJHlTFTaI13HNgSA7VwAnUUIzfoJoM4BEY8HJCkZtKGbkP8a/yqA/VVtF20OBvLzieQNIo4O1gReGhWNkx7qSsLiBp+v0nI0bDV/8jCGKnghtEdMcPVE0k8O6jqTsl4pArlpt6SV8oq/1UUtpazXZ/ccVCWs8ScxzEvZNCdIMF5IYAFt65gYgd2UkhHE9ZF3Gbpk1dU+/e1KTy8lPTPCksptQrKbaQGcLslk3UnJLeH22g41y3Hi3I9izuBed3GjeZZ578VYBCg9kRbek8ZNlfO9r1Hl9mhv3l6GRay2CiOD9SKfgMxJa2vREVQ3sb2PDryIbQw+4Kh+Ok/NVejLKskXSCcijkrUCiaeAl02AK7TXCU1kzm7IgLyeCVsbM23SL5mGp/DfB1wgd9DWH/GLi4CXILbXnoICBlfNfGKpQjyDA63P9SN4y4SSNLQV
  template:
    metadata:
      name: db-secret
      namespace: default

