apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: mysql
spec:
  nodeSelector: n2
  selector:
    matchLabels:
      app: mysql
  replicas: 4
  template:
    metadata:
      labels:
        app: mysql
    spec:
      nodeSelector: 
        - selector: db=true 
      containers:
        - name: mysql
          image: mysql:latest
          env:
            - name: MYSQL_DATABASE
              value: 'Broidery-api-db'
            - name: MYSQL_USER
              value: 'broidery-user'
            - name: MYSQL_PASSWORD
              value: 'gQ93Q1ihANsg+Nmp'
            - name: MYSQL_ROOT_PASSWORD
              value: "EGwyETUz+eUOGuDe"
          ports:
            - containerPort: 3306
              name: mysql
          volumeMounts:
            - name: mysql-persistent-storage
              mountPath: /var/lib/mysql
      volumes:
        - name: mysql-persistent-storage
          hostPath:
            path: /mnt/data/mysql
            type: DirectoryOrCreate

