kind: Role
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  namespace: ingress-nginx  # El namespace donde está el controlador de Ingress-Nginx
  name: prometheus-role
rules:
  - apiGroups: [""]
    resources: ["services", "endpoints", "pods"]
    verbs: ["get", "list"]
  - apiGroups: [""]
    resources: ["services"]
    verbs: ["get", "list"]
  - apiGroups: [""]
    resources: ["configmaps"]
    verbs: ["get"]
  - apiGroups: ["extensions"]
    resources: ["ingresses"]
    verbs: ["get", "list"]
  - apiGroups: ["networking.k8s.io"]
    resources: ["ingresses"]
    verbs: ["get", "list"]
  # Añade más reglas según las necesidades de monitoreo del controlador de Ingress-Nginx
