# Certificates deployment
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- certificates.namespace.yaml
- cluster-issuer-selfsigned.cluster-issuer.cert-manager.yaml
- wildcard.deimos.cloud-tls.certificate.cert-manager.yaml
- broidery.deimos.cloud-tls.certificate.cert-manager.yaml
- argcod.cloud-tls.certificate.cert-manager.yaml