apiVersion: batch/v1
kind: Job
metadata:
  name: checker
  #annotations:
  #  argocd.argoproj.io/hook: PostSync
  #  argocd.argoproj.io/hook-delete-policy: HookSucceeded 
  #  argocd.argoproj.io/sync-wave: "1"
spec:
  template:
    spec:
      containers:
        - name: check-1
          image: alpine/curl:latest
          command: ["curl", "-k", "-H", "broidery-backend.k3s", "https://192.168.64.26/health-check"]
        - name: check-2
          image: alpine/curl:latest
          command: ["curl", "-k", "-H", "broidery-backend.k3s", "https://192.168.64.26/health-check"]
        - name: check-3
          image: alpine/curl:latest
          command: ["curl", "-k", "-H", "broidery-backend.k3s", "https://192.168.64.26/health-check"]
        - name: check-4
          image: alpine/curl:latest
          command: ["curl", "-k", "-H", "broidery-backend.k3s", "https://192.168.64.26/health-check"]
        - name: check-5
          image: alpine/curl:latest
          command: ["curl", "-k", "-H", "broidery-backend.k3s", "https://192.168.64.26/health-check"]
        - name: check-6
          image: alpine/curl:latest
          command: ["curl", "-k", "-H", "broidery-backend.k3s", "https://192.168.64.26/health-check"]
        - name: check-7
          image: alpine/curl:latest
          command: ["curl", "-k", "-H", "broidery-backend.k3s", "https://192.168.64.26/health-check"]
        - name: check-8
          image: alpine/curl:latest
          command: ["curl", "-k", "-H", "broidery-backend.k3s", "https://192.168.64.26/health-check"]
      restartPolicy: Never