apiVersion: batch/v1
kind: Job
metadata:
  name: hey
  annotations:
    argocd.argoproj.io/hook: PostSync
    argocd.argoproj.io/hook-delete-policy: HookSucceeded 
    argocd.argoproj.io/sync-wave: "1"
spec:
  template:
    spec:
      containers:
        - name: upgrade-sql-schema
          image: williamyeh/hey:latest
          command: ["hey", "-n", "10000", "-c", "10", "http://broidery-backend.default:5000/health-check"]
      restartPolicy: Never