apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

patches:
- path: rollout.yaml
#- path: deploy.yaml

images:
- name: spirito/broidery-be
  newTag: new-feature-2

resources:
- ../../base
- sealed-secret.yaml

namespace: default
