---
apiVersion: argoproj.io/v1alpha1
kind: Rollout
metadata:
  name: broidery-backend
spec:
  selector:
    matchLabels:
      app: broidery-backend
  template:
    metadata:
      labels:
        app: broidery-backend
    spec:
      containers:
      - image: spirito/broidery-be:latest
        env:
          - name: CORS_URL
            value: 'https://broidery.k3s'
          - name: DEFAULT_CONNECTION
            valueFrom:
              secretKeyRef:
                name: default-connection
                key: DEFAULT_CONNECTION
        name: broidery-backend
  strategy:
    canary:
      stableService: broidery-backend
      canaryService: broidery-backend-canary
      trafficRouting:
        ambassador:
          mappings:
            - broidery-backend
      steps:
      - setWeight: 30
      - pause: {}
      - setWeight: 60
      - pause: {}
      - setWeight: 100
      - pause: {}     