apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: local-path-pvc
  namespace: default
spec:
  accessModes:
    #- ReadWriteOnce
    - ReadWriteMany
  storageClassName: local-path
  resources:
    requests:
      storage: 1Gi
