apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

patches:
- path: deploy.yaml

images:
- name: sleeyax/stremio-streaming-server
  newTag: latest

resources:
- ../../base

namespace: stremio