apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- broidery-project.yaml
- certs-project.yaml
- kubesystem-project.yaml
- letsencrypt-project.yaml
- metallb-project.yaml
- nginx-project.yaml
- stremio-project.yaml


